name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  repo1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./repo1
        
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install
      - run: yarn test --coverage
  repo2:
    needs: [repo1]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./repo2
        
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install
      - run: yarn test --coverage

